import Script from "next/script"
import { Poppins } from 'next/font/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
     <html lang="en" className={poppins.className}>
      
      
      <body className="min-h-screen flex items-center justify-center bg-gradient-to-br from-gray-50 via-white to-gray-100 text-gray-800 antialiased">
        {children}
      </body>
      <Script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4" />
    </html>
  )
}
